name: gen3d
dependencies:
  - python=3.9
  - pip
  - graphviz
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.8.0
      - torchvision==0.23.0
      - torchaudio==2.8.0
      - Flask==3.1.2
      - Flask-Cors==6.0.1
      - Flask-RESTful==0.3.10
      - trimesh==4.9.0
      - pyvista[all]==0.46.4
      - pymeshlab==2024.12
      - pandas==2.3.3
      - matplotlib==3.9.4
      - numpy==2.0.2
      - scipy==1.13.1
      - scikit-learn==1.6.1
      - pillow==11.3.0
      - open3d==0.19.0
      - ninja==1.13.0
      - ipykernel==6.31.0
      - djlint==1.36.4
      - openpyxl==3.1.5
      - h5py==3.14.0
      - seaborn==0.13.2
      - pytorch-metric-learning==2.9.0
      - torchdiffeq==0.2.5
      - torchviz==0.0.3
      - graphviz==0.21
      - onnx==1.17.0
      - ./app/modules/pytorch_pcd_metrics/pytorch_structural_losses
      - ./app/modules/pytorch_pcd_metrics/pytorch-emd
